FROM python:3.11-slim

WORKDIR /app

# Instala dependências necessárias para frontend
COPY requirements.txt .
RUN pip install --no-cache-dir streamlit streamlit-extras requests

# Copia código frontend
COPY src/frontend ./src/frontend

# Expõe porta do Streamlit
EXPOSE 8501

# Comando de inicialização
CMD ["streamlit", "run", "src/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

